[package]
name = "cli_yahtzee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
rand = "0.8.0"
rand_pcg = "0.3.1"